package com.coombu.photobook.model;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import com.coombu.photobook.model.lookup.ActivityType;

// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * Address generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "activity_history")
public class ActivityHistory implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ACTIVITY_HISTORY_ID", unique = true, nullable = false)
	private int activityHistoryId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EVENT_ID", nullable = false)
	private Event event;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ACTIVITY_TYPE_ID", nullable = false)
	private ActivityType activityType;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "INITIATOR_USER_ID", nullable = false)
	private SecurityUser initiator;

	@Column(name = "IMPACTED_COMPONENT_ID", nullable = false)
	private long componentId;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "IMPACTED_USER_ID", nullable = false)
	private SecurityUser impactedUser;
	
	@Column(name = "CREATE_TMSTMP",  length = 19)
	protected Timestamp createTimestamp;
	
	@Column(name = "CREATED_BY", nullable = false)
	protected Long createdBy;
	

	public ActivityHistory() {

	}

	public ActivityHistory(Event event, ActivityType activityType,
			SecurityUser initiator, long componentId,
			SecurityUser impactedUser, Timestamp createdTimestamp,
			long createdBy) {
		this.event = event;
		this.activityType = activityType;
		this.initiator = initiator;
		this.componentId = componentId;
		this.impactedUser = impactedUser;
		this.createTimestamp = createdTimestamp;
		this.createdBy = createdBy;
	}

	public int getActivityHistoryId() {
		return activityHistoryId;
	}

	public void setActivityHistoryId(int activityHistoryId) {
		this.activityHistoryId = activityHistoryId;
	}

	public Event getEvent() {
		return event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public ActivityType getActivityType() {
		return activityType;
	}

	public void setActivityType(ActivityType activityType) {
		this.activityType = activityType;
	}

	public SecurityUser getInitiator() {
		return initiator;
	}

	public void setInitiator(SecurityUser initiator) {
		this.initiator = initiator;
	}

	public long getComponentId() {
		return componentId;
	}

	public void setComponentId(long componentId) {
		this.componentId = componentId;
	}

	public SecurityUser getImpactedUser() {
		return impactedUser;
	}

	public void setImpactedUser(SecurityUser impactedUser) {
		this.impactedUser = impactedUser;
	}
	/* (non-Javadoc)
	 * @see com.coombu.photobook.model.Auditable#getCreateTimestamp()
	 */
	@XmlTransient
	public Timestamp getCreateTimestamp() {
		return this.createTimestamp;
	}

        /* (non-Javadoc)
		 * @see com.coombu.photobook.model.Auditable#setCreateTimestamp(java.sql.Timestamp)
		 */
	public void setCreateTimestamp(Timestamp createTimestamp) {
		this.createTimestamp = createTimestamp;
	}

	/* (non-Javadoc)
	 * @see com.coombu.photobook.model.Auditable#getCreatedBy()
	 */
	@XmlTransient
	public Long getCreatedBy() {
		return this.createdBy;
	}

        /* (non-Javadoc)
		 * @see com.coombu.photobook.model.Auditable#setCreatedBy(int)
		 */
	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

}
