package com.coombu.photobook.model;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.LinkedHashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * Address generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "address")
public class Address extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ADDRESS_ID", unique = true, nullable = false)
	private int addressId;

	@Column(name = "ADDRESS1", nullable = false, length = 55)
	private String address1;

	@Column(name = "ADDRESS2", length = 35)
	private String address2;

	@Column(name = "CITY", nullable = false, length = 35)
	private String city;

	@Column(name = "STATE", nullable = false, length = 35)
	private String state;

	@Column(name = "COUNTRY_ID", nullable = false)
	private short countryId;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	private Set<UserAddress> userAddresses = new LinkedHashSet<UserAddress>(0);

	public Address() {
	}

	public Address(int addressId, String address1, String city, String state,
			short countryId, Timestamp createTimestamp, long createdBy) {
		this.addressId = addressId;
		this.address1 = address1;
		this.city = city;
		this.state = state;
		this.countryId = countryId;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
	}

	public Address(int addressId, String address1, String address2,
			String city, String state, short countryId, Timestamp createTimestamp,
			long createdBy, Timestamp updateTimestamp, Long updatedBy,
			Set<UserAddress> userAddresses) {
		this.addressId = addressId;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state = state;
		this.countryId = countryId;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
		this.updateTimestamp = updateTimestamp;
		this.updatedBy = updatedBy;
		this.userAddresses = userAddresses;
	}

	@XmlElement
	public int getAddressId() {
		return this.addressId;
	}

	public void setAddressId(int addressId) {
		this.addressId = addressId;
	}

	@XmlElement
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@XmlElement
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@XmlElement
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@XmlElement
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@XmlElement
	public short getCountryId() {
		return this.countryId;
	}

	public void setCountryId(short countryId) {
		this.countryId = countryId;
	}

	@XmlTransient
	public Set<UserAddress> getUserAddresses() {
		return this.userAddresses;
	}

	public void setUserAddresses(Set<UserAddress> userAddresses) {
		this.userAddresses = userAddresses;
	}

}
