package com.coombu.photobook.model;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book")
public class Book extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "BOOK_ID", unique = true, nullable = false)
	private int bookId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EVENT_ID", nullable = false)
	private Event event;

	@Column(name = "BOOK_STATUS_ID", nullable = false)
	private byte bookStatusId;

	@Column(name = "BOOK_NAME", nullable = false, length = 45)
	private String bookName;

	@Column(name = "BOOK_FILE_NAME", nullable = false, length = 128)
	private String bookFileName;

	@Column(name = "BOOK_FILE_PATH", nullable = false, length = 256)
	private String bookFilePath;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PUBLISH_DATE", length = 19)
	private Date publishDate;


	public Book() {
	}

	public Book(int bookId, Event event, byte bookStatusId, String bookName,
			String bookFileName, String bookFilePath, Timestamp createTimestamp,
			long createdBy) {
		this.bookId = bookId;
		this.event = event;
		this.bookStatusId = bookStatusId;
		this.bookName = bookName;
		this.bookFileName = bookFileName;
		this.bookFilePath = bookFilePath;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
	}

	public Book(int bookId, Event event, byte bookStatusId, String bookName,
			String bookFileName, String bookFilePath, Date publishDate,
			Timestamp createTimestamp, long createdBy, Timestamp updateTimestamp,
			Long updatedBy) {
		this.bookId = bookId;
		this.event = event;
		this.bookStatusId = bookStatusId;
		this.bookName = bookName;
		this.bookFileName = bookFileName;
		this.bookFilePath = bookFilePath;
		this.publishDate = publishDate;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
		this.updateTimestamp = updateTimestamp;
		this.updatedBy = updatedBy;
	}

	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public byte getBookStatusId() {
		return this.bookStatusId;
	}

	public void setBookStatusId(byte bookStatusId) {
		this.bookStatusId = bookStatusId;
	}

	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	public String getBookFileName() {
		return this.bookFileName;
	}

	public void setBookFileName(String bookFileName) {
		this.bookFileName = bookFileName;
	}

	public String getBookFilePath() {
		return this.bookFilePath;
	}

	public void setBookFilePath(String bookFilePath) {
		this.bookFilePath = bookFilePath;
	}

	public Date getPublishDate() {
		return this.publishDate;
	}

	public void setPublishDate(Date publishDate) {
		this.publishDate = publishDate;
	}


}
