package com.coombu.photobook.model;

import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * CollegeRegistrationRequest generated by hbm2java
 */
@Entity
@Table(name = "college_registration_request")
public class CollegeRegistrationRequest extends AuditTrail implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "COLLEGE_REGISTRATION_REQUEST_ID", unique = true, nullable = false)
	private int collegeRegistrationRequestId;

	@Column(name = "FIRST_NAME", nullable = false, length = 35)
	private String firstName;

	@Column(name = "LAST_NAME", nullable = false, length = 35)
	private String lastName;

	@Column(name = "COLLEGE_NAME", nullable = false, length = 55)
	private String collegeName;

	@Column(name = "ADDRESS1", nullable = false, length = 55)
	private String address1;

	@Column(name = "ADDRESS2", length = 35)
	private String address2;

	@Column(name = "CITY", nullable = false, length = 35)
	private String city;

	@Column(name = "STATE", nullable = false, length = 35)
	private String state;

	@Column(name = "PRIMARY_CONTACT_NUMBER", nullable = false, length = 15)
	private String primaryContactNumber;

	@Column(name = "COUNTRY", nullable = false)
	private int country;

	@Column(name = "SECONDARY_CONTACT_NUMBER", nullable = false, length = 15)
	private String secondaryContactNumber;

	@Column(name = "EMAIL", nullable = false)
	private String email;

	@Column(name = "COLLEGE_YEAR", nullable = false)
	private short collegeYear;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AVAILABLE_CALL_DATE_TIME", nullable = false, length = 19)
	private Date availableCallDateTime;
	
	@Column(name = "SCANNED_ID_PICTURE")
	private byte[] scannedIdPicture;


	public CollegeRegistrationRequest() {
	}

	public CollegeRegistrationRequest(int collegeRegistrationRequestId,
			String firstName, String lastName, String collegeName,
			String address1, String city, String state, int country,
			String primaryContactNumber, String secondaryContactNumber,
			String email, short collegeYear, Date availableCallDateTime,
			Timestamp createTimestamp, long createdBy) {
		this.collegeRegistrationRequestId = collegeRegistrationRequestId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.collegeName = collegeName;
		this.address1 = address1;
		this.city = city;
		this.state = state;
		this.country = country;
		this.primaryContactNumber = primaryContactNumber;
		this.secondaryContactNumber = secondaryContactNumber;
		this.email = email;
		this.collegeYear = collegeYear;
		this.availableCallDateTime = availableCallDateTime;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
	}

	public CollegeRegistrationRequest(int collegeRegistrationRequestId,
			String firstName, String lastName, String collegeName,
			String address1, String address2, String city, String state,
			int country, String primaryContactNumber,
			String secondaryContactNumber, String email, short collegeYear,
			Date availableCallDateTime, byte[] scannedIdPicture,
			Timestamp createTimestamp, long createdBy, Timestamp updateTimestamp,
			Long updatedBy) {
		this.collegeRegistrationRequestId = collegeRegistrationRequestId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.collegeName = collegeName;
		this.address1 = address1;
		this.address2 = address2;
		this.city = city;
		this.state = state;
		this.country = country;
		this.primaryContactNumber = primaryContactNumber;
		this.secondaryContactNumber = secondaryContactNumber;
		this.email = email;
		this.collegeYear = collegeYear;
		this.availableCallDateTime = availableCallDateTime;
		this.scannedIdPicture = scannedIdPicture;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
		this.updateTimestamp = updateTimestamp;
		this.updatedBy = updatedBy;
	}

	public int getCollegeRegistrationRequestId() {
		return this.collegeRegistrationRequestId;
	}

	public void setCollegeRegistrationRequestId(int collegeRegistrationRequestId) {
		this.collegeRegistrationRequestId = collegeRegistrationRequestId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getCollegeName() {
		return this.collegeName;
	}

	public void setCollegeName(String collegeName) {
		this.collegeName = collegeName;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public int getCountry() {
		return this.country;
	}

	public void setCountry(int country) {
		this.country = country;
	}

	public String getPrimaryContactNumber() {
		return this.primaryContactNumber;
	}

	public void setPrimaryContactNumber(String primaryContactNumber) {
		this.primaryContactNumber = primaryContactNumber;
	}

	public String getSecondaryContactNumber() {
		return this.secondaryContactNumber;
	}

	public void setSecondaryContactNumber(String secondaryContactNumber) {
		this.secondaryContactNumber = secondaryContactNumber;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public short getCollegeYear() {
		return this.collegeYear;
	}

	public void setCollegeYear(short collegeYear) {
		this.collegeYear = collegeYear;
	}

	public Date getAvailableCallDateTime() {
		return this.availableCallDateTime;
	}

	public void setAvailableCallDateTime(Date availableCallDateTime) {
		this.availableCallDateTime = availableCallDateTime;
	}

	public byte[] getScannedIdPicture() {
		return this.scannedIdPicture;
	}

	public void setScannedIdPicture(byte[] scannedIdPicture) {
		this.scannedIdPicture = scannedIdPicture;
	}


}
