package com.coombu.photobook.model;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * CommentVote generated by hbm2java
 */
@Entity
@Table(name = "comment_vote", uniqueConstraints = @UniqueConstraint(columnNames = {
		"COMMENT_ID", "EVENT_SECURITY_USER_ID", "VOTE_TYPE_ID" }))
public class CommentVote extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "COMMENT_VOTE_ID", unique = true, nullable = false)
	private int commentVoteId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COMMENT_ID", nullable = false)
	private Comment comment;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EVENT_SECURITY_USER_ID", nullable = false)
	private EventSecurityUser eventSecurityUser;

	@Column(name = "VOTE_TYPE_ID", nullable = false)
	private int voteTypeId;


	public CommentVote() {
	}

	public CommentVote(int commentVoteId, Comment comment,
			EventSecurityUser eventSecurityUser, int voteTypeId,
			Timestamp createTimestamp, long createdBy) {
		this.commentVoteId = commentVoteId;
		this.comment = comment;
		this.eventSecurityUser = eventSecurityUser;
		this.voteTypeId = voteTypeId;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
	}

	public CommentVote(int commentVoteId, Comment comment,
			EventSecurityUser eventSecurityUser, int voteTypeId,
			Timestamp createTimestamp, long createdBy, Timestamp updateTimestamp,
			Long updatedBy) {
		this.commentVoteId = commentVoteId;
		this.comment = comment;
		this.eventSecurityUser = eventSecurityUser;
		this.voteTypeId = voteTypeId;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
		this.updateTimestamp = updateTimestamp;
		this.updatedBy = updatedBy;
	}

	public int getCommentVoteId() {
		return this.commentVoteId;
	}

	public void setCommentVoteId(int commentVoteId) {
		this.commentVoteId = commentVoteId;
	}

	public Comment getComment() {
		return this.comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public EventSecurityUser getEventSecurityUser() {
		return this.eventSecurityUser;
	}

	public void setEventSecurityUser(EventSecurityUser eventSecurityUser) {
		this.eventSecurityUser = eventSecurityUser;
	}

	public int getVoteTypeId() {
		return this.voteTypeId;
	}

	public void setVoteTypeId(int voteTypeId) {
		this.voteTypeId = voteTypeId;
	}


}
