package com.coombu.photobook.model;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * EventTemplate generated by hbm2java
 */
@Entity
@Table(name = "event_template", uniqueConstraints = {
		@UniqueConstraint(columnNames = "TEMPLATE_ID"),
		@UniqueConstraint(columnNames = "EVENT_ID") })
public class EventTemplate extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "EVENT_TEMPLATE_ID", unique = true, nullable = false)
	private int eventTemplateId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TEMPLATE_ID", unique = true, nullable = false)
	private Template template;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EVENT_ID", unique = true, nullable = false)
	private Event event;


	public EventTemplate() {
	}

	public EventTemplate(int eventTemplateId, Template template, Event event,
			Timestamp createTimestamp, long createdBy) {
		this.eventTemplateId = eventTemplateId;
		this.template = template;
		this.event = event;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
	}

	public EventTemplate(int eventTemplateId, Template template, Event event,
			Timestamp createTimestamp, long createdBy, Timestamp updateTimestamp,
			Long updatedBy) {
		this.eventTemplateId = eventTemplateId;
		this.template = template;
		this.event = event;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
		this.updateTimestamp = updateTimestamp;
		this.updatedBy = updatedBy;
	}

	public int getEventTemplateId() {
		return this.eventTemplateId;
	}

	public void setEventTemplateId(int eventTemplateId) {
		this.eventTemplateId = eventTemplateId;
	}

	public Template getTemplate() {
		return this.template;
	}

	public void setTemplate(Template template) {
		this.template = template;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}


}
