package com.coombu.photobook.model;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * ImageVote generated by hbm2java
 */
@Entity
@Table(name = "image_vote", uniqueConstraints = @UniqueConstraint(columnNames = {
		"IMAGE_ID", "EVENT_SECURITY_USER_ID", "VOTE_TYPE_ID" }))
public class ImageVote extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "IMAGE_VOTE_ID", unique = true, nullable = false)
	private int imageVoteId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IMAGE_ID", nullable = false)
	private Image image;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EVENT_SECURITY_USER_ID", nullable = false)
	private EventSecurityUser eventSecurityUser;

	@Column(name = "VOTE_TYPE_ID", nullable = false)
	private int voteTypeId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EVENT_ID", nullable = false)
	private Event event;
	
	public ImageVote() {
	}

	public ImageVote(int imageVoteId, Image image,
			EventSecurityUser eventSecurityUser, int voteTypeId,
			Timestamp createTimestamp, long createdBy) {
		this.imageVoteId = imageVoteId;
		this.image = image;
		this.eventSecurityUser = eventSecurityUser;
		this.voteTypeId = voteTypeId;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
	}

	public ImageVote(int imageVoteId, Image image,
			EventSecurityUser eventSecurityUser, int voteTypeId,
			Timestamp createTimestamp, long createdBy, Timestamp updateTimestamp,
			Long updatedBy) {
		this.imageVoteId = imageVoteId;
		this.image = image;
		this.eventSecurityUser = eventSecurityUser;
		this.voteTypeId = voteTypeId;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
		this.updateTimestamp = updateTimestamp;
		this.updatedBy = updatedBy;
	}

	public int getImageVoteId() {
		return this.imageVoteId;
	}

	public void setImageVoteId(int imageVoteId) {
		this.imageVoteId = imageVoteId;
	}

	public Image getImage() {
		return this.image;
	}

	public void setImage(Image image) {
		this.image = image;
	}

	public EventSecurityUser getEventSecurityUser() {
		return this.eventSecurityUser;
	}

	public void setEventSecurityUser(EventSecurityUser eventSecurityUser) {
		this.eventSecurityUser = eventSecurityUser;
	}

	public int getVoteTypeId() {
		return this.voteTypeId;
	}

	public void setVoteTypeId(int voteTypeId) {
		this.voteTypeId = voteTypeId;
	}

	public Event getEvent() {
		return event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}


}
