package com.coombu.photobook.model;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * PasswordHistory generated by hbm2java
 */
@Entity
@Table(name = "password_history")
public class PasswordHistory extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "PASSWORD_HISTORY_ID", unique = true, nullable = false)
	private int passwordHistoryId;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECURITY_USER_ID", nullable = false)
	private SecurityUser securityUser;

	@Column(name = "OLD_PASSWORD_HASH", nullable = false, length = 256)
	private String oldPasswordHash;
	
	@Column(name = "RESET_TMSTMP", nullable = false, length = 19)
	private Timestamp resetTimestamp;


	public PasswordHistory() {
	}

	public PasswordHistory(int passwordHistoryId, SecurityUser securityUser,
			String oldPasswordHash, Timestamp resetTimestamp, Timestamp createTimestamp,
			long createdBy) {
		this.passwordHistoryId = passwordHistoryId;
		this.securityUser = securityUser;
		this.oldPasswordHash = oldPasswordHash;
		this.resetTimestamp = resetTimestamp;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
	}

	public PasswordHistory(int passwordHistoryId, SecurityUser securityUser,
			String oldPasswordHash, Timestamp resetTimestamp, Timestamp createTimestamp,
			long createdBy, Timestamp updateTimestamp, Long updatedBy) {
		this.passwordHistoryId = passwordHistoryId;
		this.securityUser = securityUser;
		this.oldPasswordHash = oldPasswordHash;
		this.resetTimestamp = resetTimestamp;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
		this.updateTimestamp = updateTimestamp;
		this.updatedBy = updatedBy;
	}

	public int getPasswordHistoryId() {
		return this.passwordHistoryId;
	}

	public void setPasswordHistoryId(int passwordHistoryId) {
		this.passwordHistoryId = passwordHistoryId;
	}

	public SecurityUser getSecurityUser() {
		return this.securityUser;
	}

	public void setSecurityUser(SecurityUser securityUser) {
		this.securityUser = securityUser;
	}

	public String getOldPasswordHash() {
		return this.oldPasswordHash;
	}

	public void setOldPasswordHash(String oldPasswordHash) {
		this.oldPasswordHash = oldPasswordHash;
	}

	public Timestamp getResetTimestamp() {
		return this.resetTimestamp;
	}

	public void setResetTimestamp(Timestamp resetTimestamp) {
		this.resetTimestamp = resetTimestamp;
	}


}
