package com.coombu.photobook.model;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * Phone generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "phone", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PHONE_USER_PROFILE_ID", "PHONE_TYPE_ID" }))
public class Phone extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "PHONE_ID", unique = true, nullable = false)
	private Long phoneId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHONE_USER_PROFILE_ID", nullable = false)
	private UserProfile userProfile;
	
	@Column(name = "PHONE_TYPE_ID", nullable = false)
	private short phoneTypeId;
	
	@Column(name = "PHONE_NUMBER", nullable = false, length = 15)
	private String phoneNumber;


	public Phone() 
	{
	
	}
	public Phone(UserProfile userProfile, short phoneTypeId)
	{
		this.userProfile = userProfile;
		this.phoneTypeId = phoneTypeId;
	}
	public Phone(Long phoneId, UserProfile userProfile, short phoneTypeId,
			String phoneNumber, Timestamp createTimestamp, long createdBy) {
		this.phoneId = phoneId;
		this.userProfile = userProfile;
		this.phoneTypeId = phoneTypeId;
		this.phoneNumber = phoneNumber;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
	}

	public Phone(Long phoneId, UserProfile userProfile, short phoneTypeId,
			String phoneNumber, Timestamp createTimestamp, long createdBy,
			Timestamp updateTimestamp, Long updatedBy) {
		this.phoneId = phoneId;
		this.userProfile = userProfile;
		this.phoneTypeId = phoneTypeId;
		this.phoneNumber = phoneNumber;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
		this.updateTimestamp = updateTimestamp;
		this.updatedBy = updatedBy;
	}

	@XmlElement
	public Long getPhoneId() {
		return this.phoneId;
	}

	public void setPhoneId(Long phoneId) {
		this.phoneId = phoneId;
	}

	@XmlTransient
	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	@XmlElement
	public short getPhoneTypeId() {
		return this.phoneTypeId;
	}

	public void setPhoneTypeId(short phoneTypeId) {
		this.phoneTypeId = phoneTypeId;
	}

	@XmlElement
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}


}
