package com.coombu.photobook.model;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * RemovalRequest generated by hbm2java
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@Table(name = "removal_request")
public class RemovalRequest extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "REMOVAL_REQUEST_ID", unique = true, nullable = false)
	private long removalRequestId;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "USER_PROFILE_ID", nullable = false)
	private UserProfile userProfile;
	
	@Column(name = "REMOVAL_REQUEST_TYPE_ID", nullable = false)
	private int removalRequestTypeId;
	
	@Column(name = "EVENT_ID", nullable = false)
	private long eventId;
	
	@Column(name = "IMAGE_COMMENT_ID", nullable = false)
	private long imageCommentId;
	
	@Column(name = "REQUEST_REASON_ID", nullable = false)
	private int requestReasonId;
	
	@Column(name = "REQUESTOR_COMMENT")
	private String requestorComment;
	
	@Column(name = "RESPONSE_COMMENT")
	private String responseComment;
	
	@Column(name = "RESOLUTION_STATUS", nullable = false)
	private short resolutionStatus;


	public RemovalRequest() {
	}

	public RemovalRequest( UserProfile userProfile,
			int removalRequestTypeId, long eventId, long imageCommentId, int requestReasonId,
			short resolutionStatus, String flagText) {		
		this.userProfile = userProfile;
		this.removalRequestTypeId = removalRequestTypeId;
		this.eventId = eventId;
		this.imageCommentId = imageCommentId;
		this.requestReasonId = requestReasonId;
		this.resolutionStatus = resolutionStatus;
		this.requestorComment = flagText;
	}
	public RemovalRequest(long removalRequestId, UserProfile userProfile,
			int removalRequestTypeId, int imageCommentId, int requestReasonId,
			short resolutionStatus, Timestamp createTimestamp, long createdBy) {
		this.removalRequestId = removalRequestId;
		this.userProfile = userProfile;
		this.removalRequestTypeId = removalRequestTypeId;
		this.imageCommentId = imageCommentId;
		this.requestReasonId = requestReasonId;
		this.resolutionStatus = resolutionStatus;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
	}

	public RemovalRequest(long removalRequestId, UserProfile userProfile,
			int removalRequestTypeId, int imageCommentId, int requestReasonId,
			String requestorComment, String responseComment,
			short resolutionStatus, Timestamp createTimestamp, long createdBy,
			Timestamp updateTimestamp, Long updatedBy) {
		this.removalRequestId = removalRequestId;
		this.userProfile = userProfile;
		this.removalRequestTypeId = removalRequestTypeId;
		this.imageCommentId = imageCommentId;
		this.requestReasonId = requestReasonId;
		this.requestorComment = requestorComment;
		this.responseComment = responseComment;
		this.resolutionStatus = resolutionStatus;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
		this.updateTimestamp = updateTimestamp;
		this.updatedBy = updatedBy;
	}

	public long getRemovalRequestId() {
		return this.removalRequestId;
	}

	public void setRemovalRequestId(long removalRequestId) {
		this.removalRequestId = removalRequestId;
	}

	public long getEventId() {
		return eventId;
	}

	public void setEventId(long eventId) {
		this.eventId = eventId;
	}

	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setyUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	public int getRemovalRequestTypeId() {
		return this.removalRequestTypeId;
	}

	public void setRemovalRequestTypeId(int removalRequestTypeId) {
		this.removalRequestTypeId = removalRequestTypeId;
	}

	public long getImageCommentId() {
		return this.imageCommentId;
	}

	public void setImageCommentId(long imageCommentId) {
		this.imageCommentId = imageCommentId;
	}

	public int getRequestReasonId() {
		return this.requestReasonId;
	}

	public void setRequestReasonId(int requestReasonId) {
		this.requestReasonId = requestReasonId;
	}

	public String getRequestorComment() {
		return this.requestorComment;
	}

	public void setRequestorComment(String requestorComment) {
		this.requestorComment = requestorComment;
	}

	public String getResponseComment() {
		return this.responseComment;
	}

	public void setResponseComment(String responseComment) {
		this.responseComment = responseComment;
	}

	public short getResolutionStatus() {
		return this.resolutionStatus;
	}

	public void setResolutionStatus(short resolutionStatus) {
		this.resolutionStatus = resolutionStatus;
	}


}
