package com.coombu.photobook.model;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * RolePrivilege generated by hbm2java
 */
@Entity
@Table(name = "role_privilege", uniqueConstraints = @UniqueConstraint(columnNames = {
		"ROLE_ID", "PRIVILEGE_ID" }))
public class RolePrivilege extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ROLE_PRIVILEGE_ID", unique = true, nullable = false)
	private int rolePrivilegeId;

	@Column(name = "ROLE_ID", nullable = false)
	private short roleId;
	
	@Column(name = "PRIVILEGE_ID", nullable = false)
	private short privilegeId;


	public RolePrivilege() {
	}

	public RolePrivilege(int rolePrivilegeId, short roleId, short privilegeId,
			Timestamp createTimestamp, long createdBy) {
		this.rolePrivilegeId = rolePrivilegeId;
		this.roleId = roleId;
		this.privilegeId = privilegeId;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
	}

	public RolePrivilege(int rolePrivilegeId, short roleId, short privilegeId,
			Timestamp createTimestamp, long createdBy, Timestamp updateTimestamp,
			Long updatedBy) {
		this.rolePrivilegeId = rolePrivilegeId;
		this.roleId = roleId;
		this.privilegeId = privilegeId;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
		this.updateTimestamp = updateTimestamp;
		this.updatedBy = updatedBy;
	}

	public int getRolePrivilegeId() {
		return this.rolePrivilegeId;
	}

	public void setRolePrivilegeId(int rolePrivilegeId) {
		this.rolePrivilegeId = rolePrivilegeId;
	}

	public short getRoleId() {
		return this.roleId;
	}

	public void setRoleId(short roleId) {
		this.roleId = roleId;
	}

	public short getPrivilegeId() {
		return this.privilegeId;
	}

	public void setPrivilegeId(short privilegeId) {
		this.privilegeId = privilegeId;
	}


}
