package com.coombu.photobook.model;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "schedule")
public class Schedule extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "SCHEDULE_ID", unique = true, nullable = false)
	private int scheduleId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EVENT_ID")
	private Event event;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPLOAD_IMAGE_START_DATETIME", nullable = false, length = 19)
	private Date uploadImageStartDatetime;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPLOAD_IMAGE_END_DATETIME", nullable = false, length = 19)
	private Date uploadImageEndDatetime;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PICTURE_AVAILABLE_START_DATETIME", nullable = false, length = 19)
	private Date pictureAvailableStartDatetime;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PICTURE_AVAILABLE_END_DATETIME", nullable = false, length = 19)
	private Date pictureAvailableEndDatetime;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BOOK_START_DATETIME", length = 19)
	private Date bookStartDatetime;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BOOK_END_DATETIME", length = 19)
	private Date bookEndDatetime;
	
	@Column(name = "UPLOAD_IMAGE_SCHEDULE_MESSAGE", nullable = false, length = 128)
	private String uploadImageScheduleMessage;
	
	@Column(name = "PICTURE_AVAILABLE_SCHEDULE_MESSAGE", nullable = false, length = 128)
	private String pictureAvailableScheduleMessage;
	
	@Column(name = "BOOK_SCHEDULE_MESSAGE", length = 128)
	private String bookScheduleMessage;


	public Schedule() {
	}

	public Schedule(int scheduleId, Date uploadImageStartDatetime,
			Date uploadImageEndDatetime, Date pictureAvailableStartDatetime,
			Date pictureAvailableEndDatetime,
			String uploadImageScheduleMessage,
			String pictureAvailableScheduleMessage, Timestamp createTimestamp,
			long createdBy) {
		this.scheduleId = scheduleId;
		this.uploadImageStartDatetime = uploadImageStartDatetime;
		this.uploadImageEndDatetime = uploadImageEndDatetime;
		this.pictureAvailableStartDatetime = pictureAvailableStartDatetime;
		this.pictureAvailableEndDatetime = pictureAvailableEndDatetime;
		this.uploadImageScheduleMessage = uploadImageScheduleMessage;
		this.pictureAvailableScheduleMessage = pictureAvailableScheduleMessage;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
	}

	public Schedule(int scheduleId, Event event, Date uploadImageStartDatetime,
			Date uploadImageEndDatetime, Date pictureAvailableStartDatetime,
			Date pictureAvailableEndDatetime, Date bookStartDatetime,
			Date bookEndDatetime, String uploadImageScheduleMessage,
			String pictureAvailableScheduleMessage, String bookScheduleMessage,
			Timestamp createTimestamp, long createdBy, Timestamp updateTimestamp,
			Long updatedBy) {
		this.scheduleId = scheduleId;
		this.event = event;
		this.uploadImageStartDatetime = uploadImageStartDatetime;
		this.uploadImageEndDatetime = uploadImageEndDatetime;
		this.pictureAvailableStartDatetime = pictureAvailableStartDatetime;
		this.pictureAvailableEndDatetime = pictureAvailableEndDatetime;
		this.bookStartDatetime = bookStartDatetime;
		this.bookEndDatetime = bookEndDatetime;
		this.uploadImageScheduleMessage = uploadImageScheduleMessage;
		this.pictureAvailableScheduleMessage = pictureAvailableScheduleMessage;
		this.bookScheduleMessage = bookScheduleMessage;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
		this.updateTimestamp = updateTimestamp;
		this.updatedBy = updatedBy;
	}

	public int getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(int scheduleId) {
		this.scheduleId = scheduleId;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Date getUploadImageStartDatetime() {
		return this.uploadImageStartDatetime;
	}

	public void setUploadImageStartDatetime(Date uploadImageStartDatetime) {
		this.uploadImageStartDatetime = uploadImageStartDatetime;
	}

	public Date getUploadImageEndDatetime() {
		return this.uploadImageEndDatetime;
	}

	public void setUploadImageEndDatetime(Date uploadImageEndDatetime) {
		this.uploadImageEndDatetime = uploadImageEndDatetime;
	}

	public Date getPictureAvailableStartDatetime() {
		return this.pictureAvailableStartDatetime;
	}

	public void setPictureAvailableStartDatetime(
			Date pictureAvailableStartDatetime) {
		this.pictureAvailableStartDatetime = pictureAvailableStartDatetime;
	}

	public Date getPictureAvailableEndDatetime() {
		return this.pictureAvailableEndDatetime;
	}

	public void setPictureAvailableEndDatetime(Date pictureAvailableEndDatetime) {
		this.pictureAvailableEndDatetime = pictureAvailableEndDatetime;
	}

	public Date getBookStartDatetime() {
		return this.bookStartDatetime;
	}

	public void setBookStartDatetime(Date bookStartDatetime) {
		this.bookStartDatetime = bookStartDatetime;
	}

	public Date getBookEndDatetime() {
		return this.bookEndDatetime;
	}

	public void setBookEndDatetime(Date bookEndDatetime) {
		this.bookEndDatetime = bookEndDatetime;
	}

	public String getUploadImageScheduleMessage() {
		return this.uploadImageScheduleMessage;
	}

	public void setUploadImageScheduleMessage(String uploadImageScheduleMessage) {
		this.uploadImageScheduleMessage = uploadImageScheduleMessage;
	}

	public String getPictureAvailableScheduleMessage() {
		return this.pictureAvailableScheduleMessage;
	}

	public void setPictureAvailableScheduleMessage(
			String pictureAvailableScheduleMessage) {
		this.pictureAvailableScheduleMessage = pictureAvailableScheduleMessage;
	}

	public String getBookScheduleMessage() {
		return this.bookScheduleMessage;
	}

	public void setBookScheduleMessage(String bookScheduleMessage) {
		this.bookScheduleMessage = bookScheduleMessage;
	}


}
