package com.coombu.photobook.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * SecurityUserRole generated by hbm2java
 */
@Entity
@Table(name = "security_user_role", uniqueConstraints = @UniqueConstraint(columnNames = {
		"SECURITY_USER_ID", "ROLE_ID" }))
public class SecurityUserRole extends AuditTrail implements
		java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "SECURITY_USER_ROLE_ID", unique = true, nullable = false)
	private int securityUserRoleId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SECURITY_USER_ID", nullable = false)
	private SecurityUser securityUser;

	@Column(name = "ROLE_ID", nullable = false)
	private short roleId;


	public SecurityUserRole() {
	}

	public SecurityUserRole(int securityUserRoleId, SecurityUser securityUser,
			short roleId) {
		this.securityUserRoleId = securityUserRoleId;
		this.securityUser = securityUser;
		this.roleId = roleId;
	}


	public int getSecurityUserRoleId() {
		return this.securityUserRoleId;
	}

	public void setSecurityUserRoleId(int securityUserRoleId) {
		this.securityUserRoleId = securityUserRoleId;
	}

	public SecurityUser getSecurityUser() {
		return this.securityUser;
	}

	public void setSecurityUser(SecurityUser securityUser) {
		this.securityUser = securityUser;
	}

	public short getRoleId() {
		return this.roleId;
	}

	public void setRoleId(short roleId) {
		this.roleId = roleId;
	}


}
