package com.coombu.photobook.model;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

// Generated Nov 3, 2013 6:30:53 PM by Hibernate Tools 4.0.0

/**
 * UserProfile generated by hbm2java
 */
@XmlRootElement
@Entity
@Table(name = "user_profile", uniqueConstraints = @UniqueConstraint(columnNames = "SECURITY_USER_ID"))
public class UserProfile extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "USER_PROFILE_ID", unique = true, nullable = false)
	private int userProfileId;

	@XmlTransient
	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SECURITY_USER_ID", unique = true, nullable = false)
	private SecurityUser securityUser;

	@Column(name = "FIRST_NAME", nullable = false, length = 35)
	private String firstName;

	@Column(name = "LAST_NAME", nullable = false, length = 35)
	private String lastName;

	@Column(name = "EMAIL_ADDRESS", nullable = false, length = 150)
	private String emailAddress;

	@Column(name = "SECONDARY_EMAIL_ADDRESS", length = 150)
	private String secondaryEmailAddress;

	@Column(name = "IMAGE_FILE_NAME", length = 255)
	private String imageFileName;

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "userProfile")
	@Cascade({ CascadeType.ALL })
	private Set<Phone> phones = new HashSet<>(0);

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "userProfile")
	@Cascade({ CascadeType.ALL })
	private Set<UserAddress> userAddresses = new LinkedHashSet<>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
	private Set<RemovalRequest> removalRequests = new HashSet<>(0);

	@Column(name = "ABOUT_ME")
	private String aboutMe;

	@Column(name = "GENDER")
	private String gender;

	@Column(name = "DOB")
	@Temporal(TemporalType.DATE)
	private Date dob;

	@Column(name = "NICK_NAME")
	private String nickName;

	@Column(name = "TAG_LINE")
	private String tagLine;

	@Column(name = "CROP_IMAGE_NAME")
	private String croppedImageName;

	public UserProfile() {
	}

	public UserProfile(int userProfileId, SecurityUser securityUser,
			String firstName, String lastName, String emailAddress,
			Timestamp createTimestamp, long createdBy) {
		this.userProfileId = userProfileId;
		this.securityUser = securityUser;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailAddress = emailAddress;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
	}

	public UserProfile(int userProfileId, SecurityUser securityUser,
			String firstName, String lastName, String emailAddress,
			String secondaryEmailAddress, Timestamp createTimestamp,
			long createdBy, Timestamp updateTimestamp, Long updatedBy,
			Set<Phone> phones, Set<UserAddress> userAddresses, String aboutMe,
			String gender, String tagLine, String nickName,
			String croppedImageName) {
		this.userProfileId = userProfileId;
		this.securityUser = securityUser;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailAddress = emailAddress;
		this.secondaryEmailAddress = secondaryEmailAddress;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
		this.updateTimestamp = updateTimestamp;
		this.updatedBy = updatedBy;
		this.phones = phones;
		this.userAddresses = userAddresses;
		this.gender = gender;
		this.aboutMe = aboutMe;
		this.tagLine = tagLine;
		this.nickName = nickName;
		this.croppedImageName = croppedImageName;
	}

	@XmlElement
	public String getCroppedImageName() {
		return croppedImageName;
	}

	public void setCroppedImageName(String croppedImageName) {
		this.croppedImageName = croppedImageName;
	}

	@XmlElement
	public int getUserProfileId() {
		return this.userProfileId;
	}

	public void setUserProfileId(int userProfileId) {
		this.userProfileId = userProfileId;
	}

	@XmlTransient
	public SecurityUser getSecurityUser() {
		return this.securityUser;
	}

	public void setSecurityUser(SecurityUser securityUser) {
		this.securityUser = securityUser;
	}

	@XmlElement
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@XmlElement
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@XmlElement
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@XmlElement
	public String getSecondaryEmailAddress() {
		return this.secondaryEmailAddress;
	}

	public void setSecondaryEmailAddress(String secondaryEmailAddress) {
		this.secondaryEmailAddress = secondaryEmailAddress;
	}

	@XmlElement
	public String getImageFileName() {
		return imageFileName;
	}

	public void setImageFileName(String fileName) {
		this.imageFileName = fileName;
	}

	@XmlElement
	public Set<Phone> getPhones() {
		return this.phones;
	}

	public void setPhones(Set<Phone> phones) {
		this.phones = phones;
	}

	@XmlElement
	public Set<UserAddress> getUserAddresses() {
		return this.userAddresses;
	}

	public void setUserAddresses(Set<UserAddress> userAddresses) {
		this.userAddresses = userAddresses;
	}

	@XmlTransient
	public Set<RemovalRequest> getRemovalRequests() {
		return this.removalRequests;
	}

	public void setRemovalRequests(Set<RemovalRequest> removalRequests) {
		this.removalRequests = removalRequests;
	}

	@XmlElement
	public String getAboutMe() {
		return aboutMe;
	}

	public void setAboutMe(String aboutMe) {
		this.aboutMe = aboutMe;
	}

	@XmlElement
	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@XmlElement
	public Date getDob() {
		return dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@XmlElement
	public String getNickName() {
		return nickName;
	}

	@XmlElement
	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getTagLine() {
		return tagLine;
	}

	public void setTagLine(String tagLine) {
		this.tagLine = tagLine;
	}

}
