package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * AddressType generated by hbm2java
 */
@Entity
@Table(name = "address_type_lkp", uniqueConstraints = {
		@UniqueConstraint(columnNames = "ADDRESS_TYPE_NAME"),
		@UniqueConstraint(columnNames = "ADDRESS_TYPE_DESCR") })
public class AddressType extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ADDRESS_TYPE_ID", unique = true, nullable = false)
	private short addressTypeId;

	@Column(name = "ADDRESS_TYPE_NAME", unique = true, nullable = false, length = 15)
	private String addressTypeName;
	
	@Column(name = "ADDRESS_TYPE_DESCR", unique = true, nullable = false, length = 45)
	private String addressTypeDescription;

	public AddressType() {
	}

	public AddressType(short addressTypeId, String addressTypeName,
			String addressTypeDescription, Date createTimestamp, long createdBy) {
		this.addressTypeId = addressTypeId;
		this.addressTypeName = addressTypeName;
		this.addressTypeDescription = addressTypeDescription;

	}

	public AddressType(short addressTypeId, String addressTypeName,
			String addressTypeDescription, Date createTimestamp, long createdBy,
			Date updateTimestamp, Long updatedBy) {
		this.addressTypeId = addressTypeId;
		this.addressTypeName = addressTypeName;
		this.addressTypeDescription = addressTypeDescription;

	}

	public short getAddressTypeId() {
		return this.addressTypeId;
	}

	public void setAddressTypeId(short addressTypeId) {
		this.addressTypeId = addressTypeId;
	}

	public String getAddressTypeName() {
		return this.addressTypeName;
	}

	public void setAddressTypeName(String addressTypeName) {
		this.addressTypeName = addressTypeName;
	}

	public String getAddressTypeDescription() {
		return this.addressTypeDescription;
	}

	public void setAddressTypeDescription(String addressTypeDescription) {
		this.addressTypeDescription = addressTypeDescription;
	}
}
