package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * BookStatusType generated by hbm2java
 */
@Entity
@Table(name = "book_status_type_lkp", uniqueConstraints = {
		@UniqueConstraint(columnNames = "BOOK_STATUS_DESCR"),
		@UniqueConstraint(columnNames = "BOOK_STATUS_NAME") })
public class BookStatusType extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "BOOK_STATUS_TYPE_LKP_ID", unique = true, nullable = false)
	private byte bookStatusTypeId;

	@Column(name = "BOOK_STATUS_NAME", unique = true, nullable = false, length = 15)
	private String bookStatusName;
	
	@Column(name = "BOOK_STATUS_DESCR", unique = true, nullable = false, length = 45)
	private String bookStatusDescription;


	public BookStatusType() {
	}

	public BookStatusType(byte bookStatusTypeId, String bookStatusName,
			String bookStatusDescription, Date createTimestamp, long createdBy) {
		this.bookStatusTypeId = bookStatusTypeId;
		this.bookStatusName = bookStatusName;
		this.bookStatusDescription = bookStatusDescription;

	}

	public BookStatusType(byte bookStatusTypeId, String bookStatusName,
			String bookStatusDescription, Date createTimestamp, long createdBy,
			Date updateTimestamp, Long updatedBy) {
		this.bookStatusTypeId = bookStatusTypeId;
		this.bookStatusName = bookStatusName;
		this.bookStatusDescription = bookStatusDescription;


	}

	public byte getBookStatusTypeId() {
		return this.bookStatusTypeId;
	}

	public void setBookStatusTypeId(byte bookStatusTypeId) {
		this.bookStatusTypeId = bookStatusTypeId;
	}

	public String getBookStatusName() {
		return this.bookStatusName;
	}

	public void setBookStatusName(String bookStatusName) {
		this.bookStatusName = bookStatusName;
	}

	public String getBookStatusDescription() {
		return this.bookStatusDescription;
	}

	public void setBookStatusDescription(String bookStatusDescription) {
		this.bookStatusDescription = bookStatusDescription;
	}

	
}
