package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * CommentStatusType generated by hbm2java
 */
@Entity
@Table(name = "comment_status_type_lkp", uniqueConstraints = {
		@UniqueConstraint(columnNames = "COMMENT_STATUS_TYPE_NAME"),
		@UniqueConstraint(columnNames = "COMMENT_STATUS_TYPE_DESCR") })
public class CommentStatusType extends AuditTrail implements
		Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "COMMENT_STATUS_TYPE_ID", unique = true, nullable = false)
	private short commentStatusTypeId;

	@Column(name = "COMMENT_STATUS_TYPE_NAME", unique = true, nullable = false, length = 15)
	private String commentStatusTypeName;
	
	@Column(name = "COMMENT_STATUS_TYPE_DESCR", unique = true, nullable = false, length = 45)
	private String commentStatusTypeDescription;


	public CommentStatusType() {
	}

	public CommentStatusType(short commentStatusTypeId,
			String commentStatusTypeName, String commentStatusTypeDescription,
			Date createTimestamp, long createdBy) {
		this.commentStatusTypeId = commentStatusTypeId;
		this.commentStatusTypeName = commentStatusTypeName;
		this.commentStatusTypeDescription = commentStatusTypeDescription;

	}

	public CommentStatusType(short commentStatusTypeId,
			String commentStatusTypeName, String commentStatusTypeDescription,
			Date createTimestamp, long createdBy, Date updateTimestamp,
			Long updatedBy) {
		this.commentStatusTypeId = commentStatusTypeId;
		this.commentStatusTypeName = commentStatusTypeName;
		this.commentStatusTypeDescription = commentStatusTypeDescription;


	}

	public short getCommentStatusTypeId() {
		return this.commentStatusTypeId;
	}

	public void setCommentStatusTypeId(short commentStatusTypeId) {
		this.commentStatusTypeId = commentStatusTypeId;
	}

	public String getCommentStatusTypeName() {
		return this.commentStatusTypeName;
	}

	public void setCommentStatusTypeName(String commentStatusTypeName) {
		this.commentStatusTypeName = commentStatusTypeName;
	}

	public String getCommentStatusTypeDescription() {
		return this.commentStatusTypeDescription;
	}

	public void setCommentStatusTypeDescription(
			String commentStatusTypeDescription) {
		this.commentStatusTypeDescription = commentStatusTypeDescription;
	}

	
}
