package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country_lkp", uniqueConstraints = @UniqueConstraint(columnNames = "COUNTRY_NAME"))
public class Country extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "COUNTRY_ID", unique = true, nullable = false)
	private short countryId;

	@Column(name = "COUNTRY_NAME", unique = true, nullable = false, length = 45)
	private String countryName;


	public Country() {
	}

	public Country(short countryId, String countryName, Date createTimestamp,
			long createdBy) {
		this.countryId = countryId;
		this.countryName = countryName;

	}

	public Country(short countryId, String countryName, Date createTimestamp,
			long createdBy, Date updateTimestamp, Long updatedBy) {
		this.countryId = countryId;
		this.countryName = countryName;


	}

	public short getCountryId() {
		return this.countryId;
	}

	public void setCountryId(short countryId) {
		this.countryId = countryId;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	
}
