package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * EventTypeTable generated by hbm2java
 */
@Entity
@Table(name = "event_type_table_lkp", uniqueConstraints = {
		@UniqueConstraint(columnNames = "EVENT_TYPE_TABLE_NAME"),
		@UniqueConstraint(columnNames = "EVENT_TYPE_DESCR") })
public class EventTypeTable extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "EVENT_TYPE_TABLE_ID", unique = true, nullable = false)
	private short eventTypeTableId;

	@Column(name = "EVENT_TYPE_TABLE_NAME", unique = true, nullable = false, length = 45)
	private String eventTypeTableName;
	
	@Column(name = "EVENT_TYPE_DESCR", unique = true, nullable = false, length = 45)
	private String eventTypeDescription;


	public EventTypeTable() {
	}

	public EventTypeTable(short eventTypeTableId, String eventTypeTableName,
			String eventTypeDescription, Date createTimestamp, long createdBy) {
		this.eventTypeTableId = eventTypeTableId;
		this.eventTypeTableName = eventTypeTableName;
		this.eventTypeDescription = eventTypeDescription;

	}

	public EventTypeTable(short eventTypeTableId, String eventTypeTableName,
			String eventTypeDescription, Date createTimestamp, long createdBy,
			Date updateTimestamp, Long updatedBy) {
		this.eventTypeTableId = eventTypeTableId;
		this.eventTypeTableName = eventTypeTableName;
		this.eventTypeDescription = eventTypeDescription;


	}

	public short getEventTypeTableId() {
		return this.eventTypeTableId;
	}

	public void setEventTypeTableId(short eventTypeTableId) {
		this.eventTypeTableId = eventTypeTableId;
	}

	public String getEventTypeTableName() {
		return this.eventTypeTableName;
	}

	public void setEventTypeTableName(String eventTypeTableName) {
		this.eventTypeTableName = eventTypeTableName;
	}

	public String getEventTypeDescription() {
		return this.eventTypeDescription;
	}

	public void setEventTypeDescription(String eventTypeDescription) {
		this.eventTypeDescription = eventTypeDescription;
	}

	
}
