package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * FileType generated by hbm2java
 */
@Entity
@Table(name = "file_type_lkp", uniqueConstraints = {
		@UniqueConstraint(columnNames = "FILE_TYPE_NAME"),
		@UniqueConstraint(columnNames = "FILE_TYPE_DESCR") })
public class FileType extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)	
	@Column(name = "FILE_TYPE_ID", unique = true, nullable = false)
	private short fileTypeId;

	@Column(name = "FILE_TYPE_NAME", unique = true, nullable = false, length = 15)
	private String fileTypeName;

	@Column(name = "FILE_TYPE_DESCR", unique = true, nullable = false, length = 45)
	private String fileTypeDescription;

	public FileType() {
	}

	public FileType(short fileTypeId, String fileTypeName,
			String fileTypeDescription, Timestamp createTimestamp,
			long createdBy) {
		this.fileTypeId = fileTypeId;
		this.fileTypeName = fileTypeName;
		this.fileTypeDescription = fileTypeDescription;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
	}

	public FileType(short fileTypeId, String fileTypeName,
			String fileTypeDescription, Timestamp createTimestamp,
			long createdBy, Timestamp updateTimestamp, Long updatedBy) {
		this.fileTypeId = fileTypeId;
		this.fileTypeName = fileTypeName;
		this.fileTypeDescription = fileTypeDescription;
		this.createTimestamp = createTimestamp;
		this.createdBy = createdBy;
		this.updateTimestamp = updateTimestamp;
		this.updatedBy = updatedBy;

	}

	public short getFileTypeId() {
		return this.fileTypeId;
	}

	public void setFileTypeId(short fileTypeId) {
		this.fileTypeId = fileTypeId;
	}

	public String getFileTypeName() {
		return this.fileTypeName;
	}

	public void setFileTypeName(String fileTypeName) {
		this.fileTypeName = fileTypeName;
	}

	public String getFileTypeDescription() {
		return this.fileTypeDescription;
	}

	public void setFileTypeDescription(String fileTypeDescription) {
		this.fileTypeDescription = fileTypeDescription;
	}

}
