package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * ImageSource generated by hbm2java
 */
@Entity
@Table(name = "image_source_lkp", uniqueConstraints = {
		@UniqueConstraint(columnNames = "IMAGE_SOURCE_NAME"),
		@UniqueConstraint(columnNames = "IMAGE_SOURCE_DESCR") })
public class ImageSource extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "IMAGE_SOURCE_ID", unique = true, nullable = false)
	private short imageSourceId;

	@Column(name = "IMAGE_SOURCE_NAME", unique = true, nullable = false, length = 15)
	private String imageSourceName;
	
	@Column(name = "IMAGE_SOURCE_DESCR", unique = true, nullable = false, length = 45)
	private String imageSourceDescription;


	public ImageSource() {
	}

	public ImageSource(short imageSourceId, String imageSourceName,
			String imageSourceDescription, Date createTimestamp, long createdBy) {
		this.imageSourceId = imageSourceId;
		this.imageSourceName = imageSourceName;
		this.imageSourceDescription = imageSourceDescription;

	}

	public ImageSource(short imageSourceId, String imageSourceName,
			String imageSourceDescription, Date createTimestamp, long createdBy,
			Date updateTimestamp, Long updatedBy) {
		this.imageSourceId = imageSourceId;
		this.imageSourceName = imageSourceName;
		this.imageSourceDescription = imageSourceDescription;


	}

	public short getImageSourceId() {
		return this.imageSourceId;
	}

	public void setImageSourceId(short imageSourceId) {
		this.imageSourceId = imageSourceId;
	}

	public String getImageSourceName() {
		return this.imageSourceName;
	}

	public void setImageSourceName(String imageSourceName) {
		this.imageSourceName = imageSourceName;
	}

	public String getImageSourceDescription() {
		return this.imageSourceDescription;
	}

	public void setImageSourceDescription(String imageSourceDescription) {
		this.imageSourceDescription = imageSourceDescription;
	}

	
}
