package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * ImageStatusType generated by hbm2java
 */
@Entity
@Table(name = "image_status_type_lkp", uniqueConstraints = {
		@UniqueConstraint(columnNames = "IMAGE_STATUS_TYPE_NAME"),
		@UniqueConstraint(columnNames = "IMAGE_STATUS_TYPE_DESCR") })
public class ImageStatusType extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "IMAGE_STATUS_TYPE_ID", unique = true, nullable = false)
	private short imageStatusTypeId;
	
	@Column(name = "IMAGE_STATUS_TYPE_NAME", unique = true, nullable = false, length = 15)
	private String imageStatusTypeName;
	
	@Column(name = "IMAGE_STATUS_TYPE_DESCR", unique = true, nullable = false, length = 45)
	private String imageStatusTypeDescription;


	public ImageStatusType() {
	}

	public ImageStatusType(short imageStatusTypeId, String imageStatusTypeName,
			String imageStatusTypeDescription, Date createTimestamp,
			long createdBy) {
		this.imageStatusTypeId = imageStatusTypeId;
		this.imageStatusTypeName = imageStatusTypeName;
		this.imageStatusTypeDescription = imageStatusTypeDescription;

	}

	public ImageStatusType(short imageStatusTypeId, String imageStatusTypeName,
			String imageStatusTypeDescription, Date createTimestamp,
			long createdBy, Date updateTimestamp, Long updatedBy) {
		this.imageStatusTypeId = imageStatusTypeId;
		this.imageStatusTypeName = imageStatusTypeName;
		this.imageStatusTypeDescription = imageStatusTypeDescription;


	}

	public short getImageStatusTypeId() {
		return this.imageStatusTypeId;
	}

	public void setImageStatusTypeId(short imageStatusTypeId) {
		this.imageStatusTypeId = imageStatusTypeId;
	}

	public String getImageStatusTypeName() {
		return this.imageStatusTypeName;
	}

	public void setImageStatusTypeName(String imageStatusTypeName) {
		this.imageStatusTypeName = imageStatusTypeName;
	}

	public String getImageStatusTypeDescription() {
		return this.imageStatusTypeDescription;
	}

	public void setImageStatusTypeDescription(String imageStatusTypeDescription) {
		this.imageStatusTypeDescription = imageStatusTypeDescription;
	}

	
}
