package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * PhoneType generated by hbm2java
 */
@Entity
@Table(name = "phone_type_lkp")
public class PhoneType extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "PHONE_TYPE_ID", unique = true, nullable = false)
	private short phoneTypeId;

	@Column(name = "PHONE_TYPE_NAME", nullable = false, length = 15)
	private String phoneTypeName;
	
	@Column(name = "PHONE_TYPE_DESCR", nullable = false, length = 45)
	private String phoneTypeDescription;


	public PhoneType() {
	}

	public PhoneType(short phoneTypeId, String phoneTypeName,
			String phoneTypeDescription, Date createTimestamp, long createdBy) {
		this.phoneTypeId = phoneTypeId;
		this.phoneTypeName = phoneTypeName;
		this.phoneTypeDescription = phoneTypeDescription;

	}

	public PhoneType(short phoneTypeId, String phoneTypeName,
			String phoneTypeDescription, Date createTimestamp, long createdBy,
			Date updateTimestamp, Long updatedBy) {
		this.phoneTypeId = phoneTypeId;
		this.phoneTypeName = phoneTypeName;
		this.phoneTypeDescription = phoneTypeDescription;


	}

	public short getPhoneTypeId() {
		return this.phoneTypeId;
	}

	public void setPhoneTypeId(short phoneTypeId) {
		this.phoneTypeId = phoneTypeId;
	}

	public String getPhoneTypeName() {
		return this.phoneTypeName;
	}

	public void setPhoneTypeName(String phoneTypeName) {
		this.phoneTypeName = phoneTypeName;
	}

	public String getPhoneTypeDescription() {
		return this.phoneTypeDescription;
	}

	public void setPhoneTypeDescription(String phoneTypeDescription) {
		this.phoneTypeDescription = phoneTypeDescription;
	}

	
}
