package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * RequestRemovalType generated by hbm2java
 */
@Entity
@Table(name = "request_removal_type_lkp", uniqueConstraints = {
		@UniqueConstraint(columnNames = "REQUEST_REMOVAL_TYPE_DESCR"),
		@UniqueConstraint(columnNames = "REQUEST_REMOVAL_TYPE_NAME") })
public class RequestRemovalType extends AuditTrail implements
		Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "REQUEST_REMOVAL_TYPE_ID", unique = true, nullable = false)
	private int requestRemovalTypeId;

	@Column(name = "REQUEST_REMOVAL_TYPE_NAME", unique = true, nullable = false, length = 15)
	private String requestRemovalTypeName;
	
	@Column(name = "REQUEST_REMOVAL_TYPE_DESCR", unique = true, nullable = false, length = 45)
	private String requestRemovalTypeDescription;


	public RequestRemovalType() {
	}

	public RequestRemovalType(int requestRemovalTypeId,
			String requestRemovalTypeName,
			String requestRemovalTypeDescription, Date createTimestamp,
			long createdBy) {
		this.requestRemovalTypeId = requestRemovalTypeId;
		this.requestRemovalTypeName = requestRemovalTypeName;
		this.requestRemovalTypeDescription = requestRemovalTypeDescription;

	}

	public RequestRemovalType(int requestRemovalTypeId,
			String requestRemovalTypeName,
			String requestRemovalTypeDescription, Date createTimestamp,
			long createdBy, Date updateTimestamp, Long updatedBy) {
		this.requestRemovalTypeId = requestRemovalTypeId;
		this.requestRemovalTypeName = requestRemovalTypeName;
		this.requestRemovalTypeDescription = requestRemovalTypeDescription;


	}

	public int getRequestRemovalTypeId() {
		return this.requestRemovalTypeId;
	}

	public void setRequestRemovalTypeId(int requestRemovalTypeId) {
		this.requestRemovalTypeId = requestRemovalTypeId;
	}

	public String getRequestRemovalTypeName() {
		return this.requestRemovalTypeName;
	}

	public void setRequestRemovalTypeName(String requestRemovalTypeName) {
		this.requestRemovalTypeName = requestRemovalTypeName;
	}

	public String getRequestRemovalTypeDescription() {
		return this.requestRemovalTypeDescription;
	}

	public void setRequestRemovalTypeDescription(
			String requestRemovalTypeDescription) {
		this.requestRemovalTypeDescription = requestRemovalTypeDescription;
	}

	
}
