package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * RequestReason generated by hbm2java
 */
@Entity
@Table(name = "request_reason_lkp", uniqueConstraints = {
		@UniqueConstraint(columnNames = "REQUEST_REASON_NAME"),
		@UniqueConstraint(columnNames = "REQUEST_REASON_DESCR") })
public class RequestReason extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "REQUEST_REASON_ID", unique = true, nullable = false)
	private int requestReasonId;

	@Column(name = "REQUEST_REASON_NAME", unique = true, nullable = false, length = 15)
	private String requestReasonName;
	
	@Column(name = "REQUEST_REASON_DESCR", unique = true, nullable = false, length = 45)
	private String requestReasonDescription;


	public RequestReason() {
	}

	public RequestReason(int requestReasonId, String requestReasonName,
			String requestReasonDescription, Date createTimestamp, long createdBy) {
		this.requestReasonId = requestReasonId;
		this.requestReasonName = requestReasonName;
		this.requestReasonDescription = requestReasonDescription;

	}

	public RequestReason(int requestReasonId, String requestReasonName,
			String requestReasonDescription, Date createTimestamp,
			long createdBy, Date updateTimestamp, Long updatedBy) {
		this.requestReasonId = requestReasonId;
		this.requestReasonName = requestReasonName;
		this.requestReasonDescription = requestReasonDescription;


	}

	public int getRequestReasonId() {
		return this.requestReasonId;
	}

	public void setRequestReasonId(int requestReasonId) {
		this.requestReasonId = requestReasonId;
	}

	public String getRequestReasonName() {
		return this.requestReasonName;
	}

	public void setRequestReasonName(String requestReasonName) {
		this.requestReasonName = requestReasonName;
	}

	public String getRequestReasonDescription() {
		return this.requestReasonDescription;
	}

	public void setRequestReasonDescription(String requestReasonDescription) {
		this.requestReasonDescription = requestReasonDescription;
	}

	
}
