package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * ResolutionStatus generated by hbm2java
 */
@Entity
@Table(name = "resolution_status_lkp", uniqueConstraints = {
		@UniqueConstraint(columnNames = "RESOLUTION_STATUS_DESCR"),
		@UniqueConstraint(columnNames = "RESOLUTION_STATUS_NAME") })
public class ResolutionStatus extends AuditTrail implements
		Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "RESOLUTION_STATUS_ID", unique = true, nullable = false)
	private short resolutionStatusId;

	@Column(name = "RESOLUTION_STATUS_NAME", unique = true, nullable = false, length = 15)
	private String resolutionStatusName;
	
	@Column(name = "RESOLUTION_STATUS_DESCR", unique = true, nullable = false, length = 45)
	private String resolutionStatusDescription;


	public ResolutionStatus() {
	}

	public ResolutionStatus(short resolutionStatusId,
			String resolutionStatusName, String resolutionStatusDescription,
			Date createTimestamp, long createdBy) {
		this.resolutionStatusId = resolutionStatusId;
		this.resolutionStatusName = resolutionStatusName;
		this.resolutionStatusDescription = resolutionStatusDescription;

	}

	public ResolutionStatus(short resolutionStatusId,
			String resolutionStatusName, String resolutionStatusDescription,
			Date createTimestamp, long createdBy, Date updateTimestamp,
			Long updatedBy) {
		this.resolutionStatusId = resolutionStatusId;
		this.resolutionStatusName = resolutionStatusName;
		this.resolutionStatusDescription = resolutionStatusDescription;


	}

	public short getResolutionStatusId() {
		return this.resolutionStatusId;
	}

	public void setResolutionStatusId(short resolutionStatusId) {
		this.resolutionStatusId = resolutionStatusId;
	}

	public String getResolutionStatusName() {
		return this.resolutionStatusName;
	}

	public void setResolutionStatusName(String resolutionStatusName) {
		this.resolutionStatusName = resolutionStatusName;
	}

	public String getResolutionStatusDescription() {
		return this.resolutionStatusDescription;
	}

	public void setResolutionStatusDescription(
			String resolutionStatusDescription) {
		this.resolutionStatusDescription = resolutionStatusDescription;
	}

	
}
