package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role_lkp", uniqueConstraints = {
		@UniqueConstraint(columnNames = "ROLE_DESCR"),
		@UniqueConstraint(columnNames = "ROLE_NAME") })
public class Role extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "ROLE_ID", unique = true, nullable = false)
	private short roleId;

	@Column(name = "ROLE_NAME", unique = true, nullable = false, length = 15)
	private String roleName;
	
	@Column(name = "ROLE_DESCR", unique = true, nullable = false, length = 45)
	private String roleDescription;


	public Role() {
	}

	public Role(short roleId, String roleName, String roleDescription,
			Date createTimestamp, long createdBy) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDescription = roleDescription;

	}

	public Role(short roleId, String roleName, String roleDescription,
			Date createTimestamp, long createdBy, Date updateTimestamp,
			Long updatedBy) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDescription = roleDescription;


	}

	public short getRoleId() {
		return this.roleId;
	}

	public void setRoleId(short roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

	
}
