package com.coombu.photobook.model.lookup;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.coombu.photobook.model.AuditTrail;
// Generated Nov 3, 2013 12:48:30 PM by Hibernate Tools 4.0.0

/**
 * VoteType generated by hbm2java
 */
@Entity
@Table(name = "vote_type_lkp", uniqueConstraints = {
		@UniqueConstraint(columnNames = "VOTE_TYPE_DESCR"),
		@UniqueConstraint(columnNames = "VOTE_TYPE_NAME") })
public class VoteType extends AuditTrail implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "VOTE_TYPE_ID", unique = true, nullable = false)
	private int voteTypeId;

	@Column(name = "VOTE_TYPE_NAME", unique = true, nullable = false, length = 15)
	private String voteTypeName;
	
	@Column(name = "VOTE_TYPE_DESCR", unique = true, nullable = false, length = 45)
	private String voteTypeDescription;


	public VoteType() {
	}

	public VoteType(int voteTypeId, String voteTypeName,
			String voteTypeDescription, Date createTimestamp, long createdBy) {
		this.voteTypeId = voteTypeId;
		this.voteTypeName = voteTypeName;
		this.voteTypeDescription = voteTypeDescription;

	}

	public VoteType(int voteTypeId, String voteTypeName,
			String voteTypeDescription, Date createTimestamp, long createdBy,
			Date updateTimestamp, Long updatedBy) {
		this.voteTypeId = voteTypeId;
		this.voteTypeName = voteTypeName;
		this.voteTypeDescription = voteTypeDescription;


	}

	public int getVoteTypeId() {
		return this.voteTypeId;
	}

	public void setVoteTypeId(int voteTypeId) {
		this.voteTypeId = voteTypeId;
	}

	public String getVoteTypeName() {
		return this.voteTypeName;
	}

	public void setVoteTypeName(String voteTypeName) {
		this.voteTypeName = voteTypeName;
	}

	public String getVoteTypeDescription() {
		return this.voteTypeDescription;
	}

	public void setVoteTypeDescription(String voteTypeDescription) {
		this.voteTypeDescription = voteTypeDescription;
	}

	
}
